---
name: Buildah
"on": workflow_dispatch
permissions: {}

jobs:
  try-buildah:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Run it
        run: |
          buildah login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} --authfile ./auth.json ghcr.io
          cat ./auth.json | jq

