name: Checksums

on:
  workflow_dispatch:

jobs:
  build:
    name: attest many subjects
    runs-on: ubuntu-latest
    permissions:
      attestations: write
      id-token: write

    steps:
      - uses: hmarr/debug-action@v2
      - uses: actions/checkout@v4
      - name: Attest artifact
        id: attest
        uses: actions/attest@v2
        env:
          INPUT_PRIVATE-SIGNING: 'true'
        with:
          subject-checksums: checksums.txt
          predicate-type: 'https://github.github.io/attestation/release/v0.1'
          predicate: '{"purl":"pkg:github-release/cli/cli@v2.67.0","repositoryId":"212613049","releaseId":"199700588"}'
