name: Attest Image (AWS ECR)

on:
  workflow_dispatch:
    inputs:
      buildx:
        description: 'Use docker buildx'
        type: boolean
        required: false
        default: true

jobs:
  build-image-dockerhub:
    name: Build & Attest
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
    env:
      REGISTRY: 123509514931.dkr.ecr.us-east-1.amazonaws.com
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - name: Build artifact
        run: date > artifact.bin

      - name: Build Dockerfile
        run: |
          cat <<EOF > Dockerfile
          FROM scratch
          COPY artifact.bin .
          EOF

      - name: Set up QEMU
        if: inputs.buildx
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: inputs.buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: arn:aws:iam::123509514931:role/GitHubAction-AssumeRole
          managed-session-policies: arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@062b18b96a7aff071d4dc91bc00c4c1a7945b076 # v2.0.1

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5.0.0
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest

      - name: Attest artifact
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: Fetch artifact index
        run: |
          oras discover --distribution-spec v1.1-referrers-tag --format json ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest | jq
