name: OIDC
on: workflow_dispatch
jobs:
  request-oidc-token:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    # Required in order to request an OIDC token
    steps:
      - uses: hmarr/debug-action@v2
      - name: Request OIDC Token
        run: |
          # Request token
          curl "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=nobody" \
            -H "Authorization: bearer ${ACTIONS_ID_TOKEN_REQUEST_TOKEN}" \
            -H "Accept: application/json; api-version=2.0" \
            -H "Content-Type: application/json" \
            --silent | jq -r '.value' > oidc_token
          echo -e "\nOIDC Token (decoded)"
          cat oidc_token | jq -R 'split(".") | .[0],.[1] | @base64d | fromjson'
      - name: IP
        run: curl --silent https://api.ipify.org
      - name: IP
        run: curl --silent https://api.ipify.org
      - name: IP
        run: curl --silent https://api.ipify.org
      - name: IP
        run: curl --silent https://api.ipify.org
      - name: IP
        run: curl --silent https://api.ipify.org
      - name: IP
        run: curl --silent https://api.ipify.org
