name: Provenance via subject-digest

on:
  workflow_dispatch:

permissions: {}

jobs:
  attest-sbom:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      attestations: write

    steps:
      # - name: Create Artifact
      #   run: |
      #     dd if=/dev/zero of=output.dat bs=1KB count=1
      #     cat output.dat | base64 > payload.dat
      - name: Attest Artifact
        uses: actions/attest-build-Provenance@v2
        with:
          subject-digest: 'sha256:7d070f6b64d9bcc530fe99cc21eaaa4b3c364e0b2d367d7735671fa202a03b32'
          subject-name: 'subject'
          sbom-path: 'sbom.json'
