name: Windows

on:
  workflow_dispatch:

permissions: {}

jobs:
  test-windows:
    runs-on: windows-latest
    permissions:
      contents: read
      id-token: write
      attestations: write
    steps:

      - name: Shasum
        run: |
          shasum --help
          touch empty
          shasum -a 256 empty
